### ISSUE TITLE
Implement Collection.Delete()

### ISSUE THREAD

**Issue by simont** [jjacquay712/GoRods#13]
Following on from the ability to create collections, we're going to need to be able to delete collections from iRODS, similar to the iRODS `irm` function.

https://docs.irods.org/4.1.8/icommands/user/#irm

**Likely options we'll need would include:**

- Recursive option, delete all subcollections, data objects, etc (though Im not sure what happens to any subcollections, etc. if you don't do a recursive delete, do these become 'orphan' files?), default would be false
- Force option, skip sending deleted items to the trash first, default would be false

The method signature might be something like this:

`func (col *Collection) Delete(force bool, recursive bool) error`

S.

**Comment by jjacquay712** [comment]
No recursive flag when deleting collection with sub collections or data objects might fail... I'll need to look into this since I don't know the behavior. I like your proposed interface, and maybe there could be other helper functions that have force and recursive defaults defined.

**Comment by jjacquay712** [comment]
```
$ irm -f test-dir
ERROR: rmCollUtil: -r option must be used for collection /tempZone/home/admin/test-dir
ERROR: rmUtil: rm error for /tempZone/home/admin/test-dir, status = -318000 status = -318000 USER_INPUT_OPTION_ERR
```

"irm" without the recursive flag on a collection fails. 

Note: Also need to consider "irmtrash" functionality.

**Comment by jjacquay712** [comment]
Proposed IRodsObj interface additions:

```
// irm -rf
Destroy() error

// irm -f {-r}
Delete(recursive bool) error

// irm {-r}
Trash(recursive bool) error

// irm {-r} {-f}
Rm(recursive bool, force bool) error
```
