### ISSUE TITLE
Recursive iput question

### ISSUE THREAD

**Issue by ianmcorvidae** [jjacquay712/GoRODS#28]
I'm not sure if something like this is implemented within GoRODS, or if it's intended that users write the path-walking and such directly. Thanks in advance!

**Comment by jjacquay712** [comment]
Hi Ian,

Thanks for the question, this is something I'll look into. I'll get back to
you in the next few weeks. I don't see reference to a recursive flag in the
GoRODS source code or documentation at the moment.

- John

**Comment by jjacquay712** [comment]
Apologies for the late reply. Recursive `iput` functionality isn't currently supported by GoRODS. I will add this to the feature request queue.

Regards,
John
