### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by RubenGarcia** [jjacquay712/GoRODS#29]
Following the instructions, compilation fails on 
$ go get github.com/jjacquay712/GoRODS 
# github.com/jjacquay712/GoRODS
/usr/bin/ld: cannot find -lc++
/usr/bin/ld: cannot find -lc++abi
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status

Standard ubuntu 18.04.1 LTS image

**Comment by RubenGarcia** [comment]
apt-get install libc++abi-dev
apt-get install libc++-dev
apt-get install libz-dev
fixed the issue. I'd recommend a comment indicating that these packages are needed in the documentation.

**Comment by jjacquay712** [comment]
Thanks for the tip @RubenGarcia. I'll go through the installation process on 18.04.1 to validate this and add to the documentation. Did you install `build-essential` by chance? Check out this Dockerfile for 16.04:
https://github.com/bioteam/minio-irods-gateway/blob/master/Dockerfile

**Comment by RubenGarcia** [comment]
Yes, build-essential is installed in the machine.
