### ISSUE TITLE
Implement Collection.CreateCollection()

### ISSUE THREAD

**Issue by jjacquay712** [jjacquay712/GoRods#6]

**Comment by jjacquay712** [comment]
jjacquay712/GoRods/commit/7bd933105a9cdedb02b80130bb58b42b59cd1477

**Comment by simont** [comment]
Quick update, the collection.CreateSubCollection() appears to work well (and as it calls CreateCollection I think that should be fine too). I haven't checked to see if it triggers any relevant iRODS PEPs for new collections.

**Comment by jjacquay712** [comment]
Thanks for the test. I'd like to eventually create a comprehensive map in the wiki for GoRods function calls -> iRODS PEP triggered.

Created a placeholder that we can fill in after more testing: https://github.com/jjacquay712/GoRods/wiki
